# Generated by Django 6.0 on 2026-01-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Calculation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("velocity", models.FloatField()),
                ("proper_time", models.FloatField()),
                ("gamma", models.FloatField()),
                ("dilated_time", models.FloatField()),
                ("created_at", models.DateTimeField()),
            ],
        ),
    ]
