# Generated by Django 6.0 on 2026-01-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_calculation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calculation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
