# Generated by Django 6.0 on 2026-01-04 16:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_calculation_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calculation",
            name="proper_time",
            field=models.FloatField(
                validators=[django.core.validators.MinValueValidator(0.0)]
            ),
        ),
        migrations.AlterField(
            model_name="calculation",
            name="velocity",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(0.9999999999),
                ]
            ),
        ),
    ]
