# Generated by Django 6.0 on 2026-03-04 14:54

import core.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_calculation_proper_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculation",
            name="calculation_type",
            field=models.CharField(
                choices=[
                    ("relativistic", "Special Relativity"),
                    ("gravitational", "Gravitational time dilation"),
                ],
                default="relativistic",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="calculation",
            name="gravitational_factor",
            field=models.FloatField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AddField(
            model_name="calculation",
            name="object_key",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="calculation",
            name="gamma",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="calculation",
            name="velocity",
            field=models.FloatField(validators=[core.models.Calculation.validate_v]),
        ),
    ]
