# Generated by Django 6.0 on 2026-03-04 23:41

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_calculation_calculation_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calculation",
            name="object_name",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="calculation",
            name="calculation_type",
            field=models.CharField(
                choices=[
                    ("relativistic", "Special Relativity"),
                    ("gravitational", "Gravitational time dilation"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="calculation",
            name="velocity",
            field=models.FloatField(
                blank=True, null=True, validators=[core.models.Calculation.validate_v]
            ),
        ),
    ]
