# Generated by Django 6.0 on 2026-03-05 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_calculation_object_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="calculation",
            name="calculation_type",
            field=models.CharField(
                choices=[
                    ("relativistic", "Relativistic time dilation"),
                    ("gravitational", "Gravitational time dilation"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
